# Generated by Django 2.2.14 on 2020-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_actions_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company", name="name", field=models.TextField(),
        ),
    ]
